
spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8071"
logging:
  level:
    com.yossavorn.accounts: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


